// Code generated by hertz generator.

package sys

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryitemdeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querylistdeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryalldeptMw() []app.HandlerFunc {
	// your code...
	return nil
}
