// Code generated by hertz generator.

package greet

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _templateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _greetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _greet0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
