// Code generated by thriftgo (0.3.12). DO NOT EDIT.

package code

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type Code int64

const (
	Code_Success       Code = 0
	Code_DBError       Code = 100000
	Code_ParamsInvalid Code = 100001
)

func (p Code) String() string {
	switch p {
	case Code_Success:
		return "Success"
	case Code_DBError:
		return "DBError"
	case Code_ParamsInvalid:
		return "ParamsInvalid"
	}
	return "<UNSET>"
}

func CodeFromString(s string) (Code, error) {
	switch s {
	case "Success":
		return Code_Success, nil
	case "DBError":
		return Code_DBError, nil
	case "ParamsInvalid":
		return Code_ParamsInvalid, nil
	}
	return Code(0), fmt.Errorf("not a valid Code default")
}

func CodePtr(v Code) *Code { return &v }
func (p *Code) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Code(result.Int64)
	return
}

func (p *Code) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
