// Code generated by thriftgo (0.3.12). DO NOT EDIT.

package code

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type Code int64

const (
	Code_Success                Code = 0
	Code_InternalErr            Code = 100000
	Code_ParamsInvalidErr       Code = 100001
	Code_AuthorizationFailedErr Code = 100002
	Code_AlreadyExistErr        Code = 100003
	Code_NotExistErr            Code = 100004
)

func (p Code) String() string {
	switch p {
	case Code_Success:
		return "Success"
	case Code_InternalErr:
		return "InternalErr"
	case Code_ParamsInvalidErr:
		return "ParamsInvalidErr"
	case Code_AuthorizationFailedErr:
		return "AuthorizationFailedErr"
	case Code_AlreadyExistErr:
		return "AlreadyExistErr"
	case Code_NotExistErr:
		return "NotExistErr"
	}
	return "<UNSET>"
}

func CodeFromString(s string) (Code, error) {
	switch s {
	case "Success":
		return Code_Success, nil
	case "InternalErr":
		return Code_InternalErr, nil
	case "ParamsInvalidErr":
		return Code_ParamsInvalidErr, nil
	case "AuthorizationFailedErr":
		return Code_AuthorizationFailedErr, nil
	case "AlreadyExistErr":
		return Code_AlreadyExistErr, nil
	case "NotExistErr":
		return Code_NotExistErr, nil
	}
	return Code(0), fmt.Errorf("not a valid Code string")
}

func CodePtr(v Code) *Code { return &v }
func (p *Code) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Code(result.Int64)
	return
}

func (p *Code) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
