system:
  port: 8000
  ip-limit-count: 10  # 次
  ip-limit-time: 60   # 秒
  db: mysql           # mysql pgsql sqlite
  redis: true

jwt:
  signing-key: secret
  expires-time: 10s    # token有效时间
  buffer-time: 20s     # token生成后，在此时间内都可以根据旧token刷新
  issuer: issuer

zap:
  director: logs
  level: debug        # debug/info/warn/error/fatal
  prefix: ""
  format: console     # json/console
  encode-level: CapitalColorLevelEncoder
  stacktrace-key: stacktrace
  stdout: true
  files: false
  show-caller: true

redis:
  address: 127.0.0.1:6379
  password: ""
  db: 0
  cluster: false
  cluster-address:
    - "192.168.1.1:7000"
    - "192.168.1.2:7000"
    - "192.168.1.3:7000"

mysql:
  path: "127.0.0.1"
  port: "3306"
  config: "charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai"
  dbname: "testdb"
  username: "root"
  password: "root"
  max-idle-conns: 10
  max-open-conns: 100
  log-level: "info"     # silent / error / warn / info
  log-zap: true

pgsql:
  path: "127.0.0.1"
  port: "5432"
  config: "sslmode=disable TimeZone=Asia/Shanghai"
  dbname: "testdb"
  username: "postgres"
  password: "postgres"
  max-idle-conns: 10
  max-open-conns: 100
  log-level: ""
  log-zap: true

sqlite:
  path: ""
  port: ""
  config: ""
  dbname: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-level: ""
  log-zap: false
