// Code generated by hertz generator.

package dept

import (
	"github.com/cloudwego/hertz/pkg/app"

	"github.com/DrReMain/cyber-base-server/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sysMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JsonWebToken(),
	}
}

func _deptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryitemdeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querylistdeptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryalldeptMw() []app.HandlerFunc {
	// your code...
	return nil
}
