// Code generated by hertz generator.

package greet

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/DrReMain/cyber-base-server/biz/common/res"
	code "github.com/DrReMain/cyber-base-server/biz/hertz_gen/common/code"
	greet "github.com/DrReMain/cyber-base-server/biz/hertz_gen/template/greet"
)

// Greet .
// @router /v1/template/greet/:name_content [GET]
func Greet(ctx context.Context, c *app.RequestContext) {
	var err error
	var req greet.GreetReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &greet.GreetRes{
			Base:   res.Base(false, code.Code_ParamsInvalid, err),
			Result: nil,
		})
		return
	}

	c.JSON(consts.StatusOK, &greet.GreetRes{
		Base:   res.Base(true, code.Code_Success),
		Result: &greet.Result{TextContent: "hello " + req.NameContent},
	})
}
