// Code generated by hertz generator.

package dept

import (
	"context"

	"github.com/DrReMain/cyber-base-server/biz/common/errc"
	"github.com/DrReMain/cyber-base-server/biz/common/res"
	dept "github.com/DrReMain/cyber-base-server/biz/hertz_gen/sys/dept"
	sys_dept_service "github.com/DrReMain/cyber-base-server/biz/service/sys/dept"
	cutils_default "github.com/DrReMain/cyber-base-server/cyber/utils/default"

	"github.com/cloudwego/hertz/pkg/app"
)

// CreateDept .
// @router /v1/sys/dept/create [POST]
func CreateDept(ctx context.Context, c *app.RequestContext) {
	var err error
	var req dept.CreateDeptReq
	r := res.NewRes(ctx, c, &req)

	err = c.BindAndValidate(&req)
	if err != nil {
		err = errc.ParamsInvalidErr.WithMsg(err.Error())
		r.Fail(err, &dept.CreateDeptRes{
			Base:   res.Base(err),
			Result: nil,
		})
		return
	}

	err = sys_dept_service.NewService(ctx, c).CreateDept(&req)
	if err != nil {
		r.Fail(err, &dept.CreateDeptRes{
			Base:   res.Base(err),
			Result: nil,
		})
		return
	}

	r.Success(&dept.CreateDeptRes{
		Base:   res.Base(),
		Result: nil,
	})
}

// UpdateDept .
// @router /v1/sys/dept/:id [PUT]
func UpdateDept(ctx context.Context, c *app.RequestContext) {
	var err error
	var req dept.UpdateDeptReq
	r := res.NewRes(ctx, c, &req)

	err = c.BindAndValidate(&req)
	if err != nil {
		r.Fail(err, &dept.UpdateDeptRes{
			Base:   res.Base(err),
			Result: nil,
		})
		return
	}

	err = sys_dept_service.NewService(ctx, c).UpdateDept(&req)
	if err != nil {
		r.Fail(err, &dept.UpdateDeptRes{
			Base:   res.Base(err),
			Result: nil,
		})
		return
	}

	r.Success(&dept.UpdateDeptRes{
		Base:   res.Base(),
		Result: nil,
	})
}

// DeleteDept .
// @router /v1/sys/dept/:id [DELETE]
func DeleteDept(ctx context.Context, c *app.RequestContext) {
	var err error
	var req dept.DeleteDeptReq
	r := res.NewRes(ctx, c, &req)

	err = c.BindAndValidate(&req)
	if err != nil {
		r.Fail(err, &dept.DeleteDeptRes{
			Base:   res.Base(err),
			Result: nil,
		})
		return
	}

	err = sys_dept_service.NewService(ctx, c).DeleteDept(&req)
	if err != nil {
		r.Fail(err, &dept.DeleteDeptRes{
			Base:   res.Base(),
			Result: nil,
		})
		return
	}

	r.Success(&dept.DeleteDeptRes{
		Base:   res.Base(),
		Result: nil,
	})
}

// QueryAllDept .
// @router /v1/sys/dept/list_all [GET]
func QueryAllDept(ctx context.Context, c *app.RequestContext) {
	var err error
	var req dept.QueryAllDeptReq
	r := res.NewRes(ctx, c, &req)

	err = c.BindAndValidate(&req)
	if err != nil {
		r.Fail(err, &dept.QueryAllDeptRes{
			Base:   res.Base(err),
			Result: nil,
		})
		return
	}

	l, err := sys_dept_service.NewService(ctx, c).QueryAllDept(&req)
	if err != nil {
		r.Fail(err, &dept.DeleteDeptRes{
			Base:   res.Base(err),
			Result: nil,
		})
		return
	}

	result := make([]*dept.Dept, 0, len(*l))
	for _, d := range *l {
		result = append(result, &dept.Dept{
			ID:       d.ID,
			DeptName: cutils_default.String(d.DeptName),
			Remark:   cutils_default.String(d.Remark),
		})
	}

	r.Success(&dept.QueryAllDeptRes{
		Base:   res.Base(),
		Result: result,
	})
}

// QueryListDept .
// @router /v1/sys/dept/list [GET]
func QueryListDept(ctx context.Context, c *app.RequestContext) {
	var err error
	var req dept.QueryListDeptReq
	r := res.NewRes(ctx, c, &req)

	err = c.BindAndValidate(&req)
	if err != nil {
		r.Fail(err, &dept.QueryListDeptRes{
			Base:   res.Base(err),
			Result: nil,
		})
		return
	}

	l, p, err := sys_dept_service.NewService(ctx, c).QueryListDept(&req)
	if err != nil {
		r.Fail(err, &dept.QueryListDeptRes{
			Base:   res.Base(err),
			Result: nil,
		})
		return
	}

	list := make([]*dept.Dept, 0, len(*l))
	for _, d := range *l {
		list = append(list, &dept.Dept{
			ID:       d.ID,
			DeptName: cutils_default.String(d.DeptName),
			Remark:   cutils_default.String(d.Remark),
		})
	}

	r.Success(&dept.QueryListDeptRes{
		Base: res.Base(),
		Result: &dept.PResult{
			P:    p.Trans(),
			List: list,
		},
	})
}

// QueryItemDept .
// @router /v1/sys/dept/:id [GET]
func QueryItemDept(ctx context.Context, c *app.RequestContext) {
	var err error
	var req dept.QueryItemDeptReq
	r := res.NewRes(ctx, c, &req)

	err = c.BindAndValidate(&req)
	if err != nil {
		r.Fail(err, &dept.QueryItemDeptRes{
			Base:   res.Base(err),
			Result: nil,
		})
		return
	}

	item, err := sys_dept_service.NewService(ctx, c).QueryItemDept(&req)
	if err != nil {
		r.Fail(err, &dept.QueryItemDeptRes{
			Base:   res.Base(err),
			Result: nil,
		})
		return
	}

	r.Success(&dept.QueryItemDeptRes{
		Base: res.Base(),
		Result: &dept.Dept{
			ID:       item.ID,
			DeptName: cutils_default.String(item.DeptName),
			Remark:   cutils_default.String(item.Remark),
		},
	})
}
