// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	sys "github.com/DrReMain/cyber-base-server/biz/router/sys"
	template_greet "github.com/DrReMain/cyber-base-server/biz/router/template/greet"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	sys.Register(r)

	template_greet.Register(r)
}
