// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	auth_account "github.com/DrReMain/cyber-base-server/biz/router/auth/account"
	sys_dept "github.com/DrReMain/cyber-base-server/biz/router/sys/dept"
	template_greet "github.com/DrReMain/cyber-base-server/biz/router/template/greet"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	auth_account.Register(r)

	sys_dept.Register(r)

	template_greet.Register(r)
}
